version: '3.8'

services:
  projet-eni-front:
    build: ./
    container_name: projet-eni-front
    networks:
      - front
    ports:
      - "80:80"
networks:
  front:
    name: front
    driver: bridge